apiVersion: v1
kind: Pod
metadata: 
  name: dng1
  labels:
    label: app
spec: 
  containers: 
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx-scn
    ports:
    - containerPort: 80
