apiVersion: v1
kind: PersistentVolume
metadata: 
  name: ngxnfspv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /nfs
    server: 192.168.43.177
