apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-ngx
spec:
  replicas: 1
  selector: 
    app: ngx
  template:
    metadata:
      labels:
        app: ngx
    spec:
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-ngx
