apiVersion: v1
kind: ReplicationController
metadata:
  name: dnginx-rc
spec:
  replicas: 1
  selector: 
    label: app
  template:
    metadata:
      labels:
        label: app
    spec:
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent
        image: nginx
        ports:
        - containerPort: 80
